basePath: /
host: localhost:8000
info:
  contact:
    email: devalexrossi@gmail.com
    name: Alex Rossi
    url: https://4lexrossi.github.io/
  description: Product API with auhtentication
  license:
    name: Lex Labs License
  termsOfService: http://swagger.io/terms/
  title: Go Expert API Example
  version: "1.0"
paths: {}
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
